language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
  email:
    on_success: always
    on_failure: never

install:
  - python setup.py install

script:
  - pytest -rsxX --cov=pyoselm --cov-report=term --cov-report=html:tests/coverage tests/

