language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

notifications:
  email:
    on_success: never
    on_failure: never

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install codecov

install:
  - pip install ".[tests]" .  # install package + test dependencies

script:
  # run tests
  - pytest --cov=pyoselm --cov-report=term --cov-report=xml --cov-report=html:tests/coverage -m "not expensive" tests/unit

after_success:
  - codecov # submit coverage

