language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

notifications:
  email:
    on_success: always
    on_failure: never

install:
  - python setup.py install

script:
  - python test/test_oselm.py # or py.test for Python versions 3.5 and below

